enableGlobalCache: false

initScope: knicks-knacks

nodeLinker: node-modules

npmRegistryServer: "https://registry.npmjs.org/"

# Enable Yarn workspace features
enableTelemetry: false

# Improve installation speed
compressionLevel: 0

# How to handle peer dependency mismatches
pnpMode: loose

# React Native specific settings
nmHoistingLimits: workspaces

# Enable scripts in workspaces
enableScripts: true

# Improve Yarn/node_modules linking for React Native
nmMode: hardlinks-local

# Handle React Native symlinks better for Expo
packageExtensions:
  # Fix peer dependency issues
  "react-native@*":
    peerDependencies:
      "@babel/core": "*"
  "@react-native-async-storage/async-storage@*":
    peerDependencies:
      "react-native": "*"
  "@react-navigation/native@*":
    peerDependencies:
      "react-native": "*"
  "@react-navigation/native-stack@*":
    peerDependencies:
      "react-native": "*"
  "expo@*":
    peerDependencies:
      "react": "*"
      "react-native": "*"

# Improve stability with packages that might have issues
logFilters:
  - code: YN0002  # Missing peer dependency
    level: discard
  - code: YN0060  # Incompatible peer dependency
    level: discard
  - code: YN0069  # Redundant peer dependency rule
    level: discard
