[phases.setup]
nixPkgs = ["nodejs", "yarn"]
nixOverlays = []

[phases.install]
cmds = ["yarn install"]

[phases.build]
cmds = ["echo Building project...", "yarn build", "ls -l dist || true"]

[phases.start]
cmds = ["echo Starting server...", "ls -l dist || true", "node dist/server.js"]