# Use phases-based config to ensure yarn is installed
[nodejs]
version = "20"

[setup]
packages = ["nodejs", "yarn-1x"]

[install]
command = "yarn install "

[build]
command = "yarn build"

[start]
command = "yarn start"