[phases.setup]
# Define necessary system packages. Node.js and Yarn are essential.
nixPkgs = ["nodejs", "yarn"]

[phases.install]
# Command to install dependencies. Nixpacks might auto-detect this
# if yarn.lock exists, but being explicit is clear.
cmds = ["yarn install"]

[phases.build]
# Command to build the project. Your package.json defines this as 'tsc'.
cmds = ["yarn build"]

[phases.start]
# The command to run the built application.
# Using 'cmd' for a single start command (common in newer Nixpacks).
# If this causes issues, we can revert to cmds = ["node dist/server.js"].
cmd = "node dist/server.js"