export const WORDS = [
  "about", "above", "abuse", "actor", "acute", "admit", "adopt", "adult",
  "after", "again", "agent", "agree", "ahead", "alarm", "album", "alert",
  "alien", "align", "alike", "alive", "allow", "alone", "along", "alter",
  "among", "anger", "angle", "angry", "apart", "apple", "apply", "arena",
  "argue", "arise", "armor", "array", "arrow", "aside", "asset", "audio",
  "audit", "avoid", "award", "aware", "awful", "bacon", "badge", "badly",
  "basic", "basin", "basis", "batch", "beach", "beard", "beast", "began",
  "begin", "being", "below", "bench", "berry", "birth", "black", "blade",
  "blame", "blank", "blast", "blaze", "bleed", "blend", "bless", "blind",
  "block", "blood", "bloom", "blown", "board", "boast", "bonus", "boost",
  "booth", "bound", "brain", "brake", "brand", "brave", "bread", "break",
  "breed", "brick", "bride", "brief", "bring", "broad", "broke", "brown",
  "brush", "build", "bunch", "burst", "buyer", "cable", "cache", "camel",
  "candy", "cargo", "carry", "carve", "catch", "cause", "chain", "chair",
  "chaos", "charm", "chart", "chase", "cheap", "check", "chess", "chest",
  "chief", "child", "china", "chord", "chunk", "civic", "civil", "claim",
  "class", "clean", "clear", "clerk", "click", "cliff", "climb", "clock",
  "close", "cloth", "cloud", "coach", "coast", "cocoa", "colon", "color",
  "comet", "comic", "coral", "couch", "cough", "could", "count", "court",
  "cover", "crack", "craft", "crane", "crash", "crawl", "crazy", "cream",
  "creek", "crest", "crime", "crisp", "cross", "crowd", "crown", "crude",
  "cruel", "crush", "cubic", "curve", "cycle", "daddy", "daily", "dairy",
  "dance", "datum", "dealt", "death", "debug", "debut", "decay", "decor",
  "deity", "delay", "delta", "dense", "depot", "depth", "derby", "desert",
  "diary", "dirty", "disco", "ditch", "dodge", "doing", "donor", "doubt",
  "dough", "dozen", "draft", "drain", "drama", "drank", "drawn", "dread",
  "dream", "dress", "dried", "drift", "drill", "drink", "drive", "drown",
  "drunk", "dummy", "dwarf", "dwell", "dying", "eager", "early", "earth",
  "eaten", "edict", "eight", "elbow", "elder", "elect", "elite", "email",
  "embed", "ember", "empty", "ended", "enemy", "enjoy", "enter", "entry",
  "equal", "equip", "erase", "error", "erupt", "essay", "event", "every",
  "exact", "exert", "exile", "exist", "extra", "fable", "facet", "faith",
  "false", "fancy", "faint", "fault", "favor", "feast", "fence", "ferry",
  "fetch", "fever", "fiber", "field", "fiery", "fifth", "fifty", "fight",
  "final", "first", "fixed", "flags", "flame", "flash", "flask", "flesh",
  "float", "flock", "flood", "floor", "flour", "flown", "fluid", "flush",
  "focus", "force", "forge", "forth", "forum", "found", "frame", "frank",
  "fraud", "fresh", "front", "frost", "fruit", "fully", "fungi", "funny",
  "giant", "given", "glass", "globe", "glory", "glove", "going", "grace",
  "grade", "grain", "grand", "grant", "grape", "graph", "grasp", "grass",
  "grave", "great", "green", "greet", "grief", "grill", "grind", "groan",
  "gross", "group", "grove", "grown", "guard", "guess", "guest", "guide",
  "guild", "guilt", "habit", "happy", "harsh", "hasn", "haste", "haunt",
  "haven", "heart", "heavy", "hedge", "hello", "hence", "herbs", "hinge",
  "hobby", "honor", "horse", "hotel", "hound", "house", "hover", "human",
  "humid", "humor", "hurry", "ideal", "image", "imply", "inbox", "index",
  "inner", "input", "intel", "inter", "intro", "issue", "ivory", "jelly",
  "jewel", "joint", "joker", "jolly", "judge", "juice", "juicy", "jumbo",
  "jumpy", "knife", "knock", "known", "label", "labor", "laden", "lance",
  "large", "laser", "later", "laugh", "layer", "leach", "leads", "learn",
  "lease", "least", "leave", "legal", "lemon", "level", "lever", "light",
  "limit", "linen", "liner", "liver", "lobby", "local", "lodge", "logic",
  "login", "loose", "lorry", "loser", "lotus", "loved", "lover", "lower",
  "loyal", "lucky", "lunar", "lunch", "lyric", "macro", "magic", "major",
  "maker", "manor", "maple", "march", "marry", "marsh", "match", "maybe",
  "mayor", "medal", "media", "melon", "mercy", "merge", "merit", "merry",
  "metal", "meter", "micro", "midst", "might", "mimic", "mince", "minor",
  "minus", "mixed", "model", "modem", "moist", "money", "month", "moral",
  "motor", "mould", "mount", "mouse", "mouth", "movie", "muddy", "multi",
  "mural", "music", "naive", "naked", "nasty", "naval", "needs", "nerve",
  "never", "newer", "newly", "night", "noble", "noise", "north", "notch",
  "noted", "novel", "nurse", "occur", "ocean", "offer", "often", "olive",
  "onion", "onset", "opera", "optic", "orbit", "order", "organ", "other",
  "ought", "outer", "outgo", "owned", "owner", "oxide", "ozone", "paint",
  "panel", "panic", "paper", "party", "pasta", "paste", "patch", "pause",
  "peace", "peach", "pearl", "pedal", "penny", "petal", "petty", "phase",
  "phone", "photo", "piano", "piece", "pilot", "pinch", "pitch", "pizza",
  "place", "plain", "plane", "plant", "plate", "plaza", "plead", "pluck",
  "plumb", "plump", "plunge", "point", "poker", "polar", "polka", "porch",
  "pound", "power", "press", "price", "pride", "prime", "print", "prior",
  "prize", "probe", "proof", "proud", "prove", "prune", "proxy", "pulse",
  "pupil", "purse", "queen", "query", "quest", "queue", "quick", "quiet",
  "quilt", "quirk", "quota", "quote", "radar", "radio", "raise", "rally",
  "ranch", "range", "rapid", "ratio", "reach", "react", "ready", "realm",
  "rebel", "refer", "reign", "relax", "relay", "relic", "reply", "rerun",
  "reset", "resin", "retro", "rider", "ridge", "rifle", "right", "rigid",
  "ripen", "risen", "risky", "rival", "river", "roast", "robot", "rocky",
  "rogue", "roman", "roost", "rouge", "rough", "round", "route", "royal",
  "rugby", "ruler", "rural", "sadly", "saint", "salad", "sales", "salon",
  "salty", "sandy", "sauce", "sauna", "scale", "scare", "scary", "scene",
  "scent", "scope", "score", "scout", "scrap", "seize", "sense", "serve",
  "setup", "seven", "shade", "shake", "shall", "shame", "shape", "share",
  "shark", "sharp", "sheep", "sheer", "sheet", "shelf", "shell", "shift",
  "shine", "shirt", "shock", "shoot", "shore", "short", "shown", "shrub",
  "siege", "sight", "sigma", "silly", "since", "siren", "sixth", "sixty",
  "skate", "skill", "skull", "slave", "sleep", "slice", "slide", "slope",
  "sloth", "small", "smart", "smell", "smile", "smoke", "snake", "solar",
  "solid", "solve", "sonic", "sorry", "sound", "south", "space", "spare",
  "spark", "spawn", "speak", "spear", "speed", "spell", "spend", "spice",
  "spicy", "spine", "spite", "split", "spoke", "spoon", "sport", "spray",
  "squad", "stack", "staff", "stage", "stain", "stair", "stake", "stall",
  "stamp", "stand", "stare", "start", "state", "stays", "steady", "steak",
  "steal", "steam", "steel", "steep", "steer", "stern", "stick", "stiff",
  "still", "stock", "stomp", "stone", "stood", "stool", "store", "storm",
  "story", "stove", "strap", "straw", "strip", "stuck", "study", "stuff",
  "style", "sugar", "suite", "sunny", "super", "surge", "swamp", "swear",
  "sweat", "sweep", "sweet", "swift", "swing", "swiss", "sword", "syrup",
  "table", "taken", "taste", "tasty", "teach", "teddy", "teeth", "tempo",
  "tenor", "tense", "tenth", "terry", "thank", "theft", "theme", "there",
  "these", "thick", "thief", "thing", "think", "third", "thorn", "those",
  "three", "threw", "throw", "thumb", "tiger", "tight", "timer", "tired",
  "title", "toast", "today", "token", "tonal", "topic", "torch", "total",
  "touch", "tough", "towel", "tower", "toxic", "trace", "track", "trade",
  "trail", "train", "trait", "trash", "treat", "trend", "trial", "tribe",
  "trick", "tried", "troop", "truck", "truly", "trunk", "trust", "truth",
  "tumor", "tuned", "tuner", "twist", "ultra", "uncle", "under", "unfold",
  "union", "unite", "unity", "until", "upper", "upset", "urban", "usage",
  "usual", "valid", "value", "valve", "vault", "vegan", "venue", "verse",
  "video", "vigor", "viral", "virus", "visit", "vista", "vital", "vivid",
  "vocal", "vodka", "vogue", "voice", "volta", "voter", "waist", "waste",
  "watch", "water", "weary", "weave", "wedge", "weigh", "weird", "whale",
  "wheat", "wheel", "where", "which", "while", "white", "whole", "whose",
  "widen", "widow", "width", "wired", "witch", "woman", "woods", "world",
  "worry", "worse", "worst", "worth", "would", "wound", "woven", "wrath",
  "wreck", "wrist", "write", "wrong", "wrote", "yacht", "yield", "young",
  "yours", "youth", "zebra", "zesty", "zones",
];

export function getRandomWord(): string {
  return WORDS[Math.floor(Math.random() * WORDS.length)].toUpperCase();
}

export function getDailyWord(): string {
  const startDate = new Date("2024-01-01").getTime();
  const today = new Date().setHours(0, 0, 0, 0);
  const dayIndex = Math.floor((today - startDate) / (1000 * 60 * 60 * 24));
  return WORDS[dayIndex % WORDS.length].toUpperCase();
}

export function isValidWord(word: string): boolean {
  return WORDS.includes(word.toLowerCase());
}
