name: Deploy CalorieCam Backend to Railway

on:
  push:
    branches:
      - main
    paths:
      - "apps/calorie-cam/backend/**"
      - ".github/workflows/deploy-calorie-cam-backend.yml"

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
      SERVICE_ID: fb872640-8aac-48b1-827b-917a61646816

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "yarn"
          cache-dependency-path: "**/yarn.lock"

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build backend
        run: |
          cd apps/calorie-cam/backend
          yarn build

      - name: Install Railway CLI
        run: npm install -g @railway/cli

      - name: Deploy to Railway
        run: |
          cd apps/calorie-cam/backend
          railway up --service=$SERVICE_ID
