name: Deploy CalorieCam Backend to Railway

on:
  push:
    branches:
      - main
      - master
    paths:
      - "apps/calorie-cam/backend/**"
      - ".github/workflows/deploy-calorie-cam-backend.yml"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8.6.12
          run_install: false

      - name: Get pnpm store directory
        id: pnpm-cache
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

      - name: Setup pnpm cache
        uses: actions/cache@v3
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      # Option 1: Install dependencies at workspace root and use workspace commands
      - name: Install all dependencies
        run: |
          pnpm install --frozen-lockfile

      - name: Build backend
        run: |
          pnpm --filter calorie-cam-backend build

      - name: Install Railway CLI
        run: npm install -g @railway/cli

      - name: Deploy to Railway
        run: |
          cd apps/calorie-cam/backend
          # First try to link the project
          railway link || echo "Could not link project automatically"
          # Then deploy regardless
          railway up --detach
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
