name: Deploy CalorieCam Backend to Railway

on:
  push:
    branches:
      - main
      - master
    paths:
      - "apps/calorie-cam/backend/**"
      - ".github/workflows/deploy-calorie-cam-backend.yml"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8.6.12
          run_install: false

      - name: Install Railway CLI
        run: npm install -g @railway/cli

      - name: Install dependencies
        run: |
          cd apps/calorie-cam/backend
          pnpm install

      - name: Build application
        run: |
          cd apps/calorie-cam/backend
          pnpm build

      - name: Deploy to Railway
        run: |
          cd apps/calorie-cam/backend
          railway up
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
